### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [MihanEntalpo/allure-single-html-file#1]
Hello!

I found this project from https://stackoverflow.com/a/70380197/5287257

Could you please add information about the license of this repository — is it allowed to copy, change and use the code in any purpose?
It would be great to see any popular open source license.

**Comment by MihanEntalpo** [comment]
Added MIT license. Thanks for the reminder

**Comment by vazhnov** [comment]
@MihanEntalpo , thank you very much!
