### ISSUE TITLE
Can not install using pip

### ISSUE THREAD

**Issue by ralupopa** [MihanEntalpo/allure-single-html-file#12]
Tried 
> pip install allure-combine in pycharm terminal and cmd.

![image](https://user-images.githubusercontent.com/62647565/174327513-5bc6279f-c489-44c9-97a5-6ee2c1d32073.png)

Should it be available already or not yet even if the feature is merged ?

**Comment by MihanEntalpo** [comment]
It seems that package wasnt uploaded to pip yet. I'll fix it tomorrow and let you know

**Comment by MihanEntalpo** [comment]
@ralupopa uploaded package to pip, usable now
