### ISSUE TITLE
Support for xml attachments

### ISSUE THREAD

**Issue by akueken** [MihanEntalpo/allure-single-html-file#15]
First of all thank you for your great work, Mihan. Your tool is really a time and life saver for me at the moment. 

Actual I am working on a lot of tests, which identifies diffs between xml files. And for better traceability the tests write xml fragments as attachment to the allure report. Sadly we get the warning, that xml ist not supported with allure-combine:

`WARNING: Unsupported extension: xml (file: ...) skipping (supported are: ['svg', 'txt', 'js', 'json', 'csv', 'css', 'html', 'htm', 'png', 'jpeg', 'jpg', 'gif', 'mp4', 'avi', 'webm']`

Would it be possible to add xml support to allure-combine? That would be incredible helpful.

Cheers,
Alexander

**Comment by MihanEntalpo** [comment]
Xml files, as other files containing tags, could bread allure app, so, for testing I'll need allure generated folder example with xml files. Would you kindly attach an example archive?

**Comment by MihanEntalpo** [comment]
Added xml attachments support in version 1.0.8, already available in pip repo.
