### ISSUE TITLE
Not a Function

### ISSUE THREAD

**Issue by Fulki88** [MihanEntalpo/allure-single-html-file#21]
Hallo thank you for a nice package, but when I running,  I got Error on 

/pathFile/node_modules/allure-single-html-file-js/src/combine-allure.js:65
     const ext = file.split('.').at(-1);
                                 ^

TypeError: file.split(...).at is not a function

and after I change to length - 1 got this error:

/pathFile/node_modules/allure-single-html-file-js/src/combine-allure.js:148
       content = `${d.content.replaceAll('\\', '\\\\').replaceAll('"', '\\"').replaceAll('\r\n', '\\n').replaceAll('\n', '\\n')
                              ^

TypeError: d.content.replaceAll is not a function

Can you fix that on the next update? thank you!

**Comment by MihanEntalpo** [comment]
Hello. What browser you are using and which version it has?

**Comment by MihanEntalpo** [comment]
Also, please attach your report in zip-archive

**Comment by MihanEntalpo** [comment]
@Fulki88 I've discovered that you are using not my script, but it's port to javascript, written by another author. 
Here is the repo, you should create issue there: https://github.com/aruiz-caritsqa/allure-single-html-file-js
