### ISSUE TITLE
Request and response attachments not showing when using allure-combine

### ISSUE THREAD

**Issue by sharathhatter1** [MihanEntalpo/allure-single-html-file#25]
**Describe the bug**
Request and response attachments not showing when generating complete.html. 

But when  generating using allure generate, all the request and response showing properly when we open index.html
.

Using version 2.21.0 both allure-rest-assured and allure-testng 2.13.18

Using  -> addFilter(new AllureRestAssured())

Screenshots using allure generate attached-
![local](https://user-images.githubusercontent.com/55090052/223065828-8cf305b7-f8e5-47a5-ae1c-8bd395221750.PNG)

Screenshot using allure-combine attached - 
![othersystemCapture](https://user-images.githubusercontent.com/55090052/223065836-495a4ede-c8c9-4b44-9291-fcae95778074.PNG)

When we see the error in the file it says unable to get html file from data/attachments folder under allure-report. It is not merging the data properly.

**Comment by MihanEntalpo** [comment]
Hello. Please, attach zip-archive of your output directory, BEFORE running allure-combine

**Comment by sharathhatter1** [comment]
Hi @MihanEntalpo, I have created allure-report 
allure generate allure-results --clean -o allure-report   

allure-report folder generated with all the data.

But when we use allure-combine, the complete.html file not including data from data->attachments folder. 
I created zip archive of the allure-report directory and running the command allure-combine shows error( attached file - unable to find index.html)


![image](https://user-images.githubusercontent.com/55090052/232974355-a6d72005-d724-4adb-98ea-644d157c5d4e.png)

**Comment by MihanEntalpo** [comment]
@sharathhatter1 it seems, that you are specifying rar-archive, not the folder

**Comment by MihanEntalpo** [comment]
According to this merged pull request https://github.com/allure-framework/allure2/pull/2072 Allure itself now has command line argument --single-file that make it produce report as a single html file. As for now it's not described in official allure docs, but anyway it should make this package (allure-combine) useless. I'm encorage you to use Allure --single-file functionality, as it should work much better that my combiner!
