### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: allure_reports/https://www.googletagmanager.com/gtag/js----

### ISSUE THREAD

**Issue by JERINEP** [MihanEntalpo/allure-single-html-file#26]
I am using the Allure npm wrapper, which can be found at "https://www.npmjs.com/package/allure-commandline". When I try to use the allure combine command with this package, I encounter a FileNotFoundError. However, if I install Allure using Homebrew, the command works fine.

**Comment by jpscigliano** [comment]
I have encountered the same problem using this allure-combine python tool. 
In the latest version of allure2 its looks like they added a new script for analitycs and this is interfiering with combine.py  [(Link to tag release](https://github.com/allure-framework/allure2/commit/f478ad78701bf32b49d1690fe237bdea38ea3e0f))

```
> Folder to process is Samsung Galaxy S21-allure-results-html

 File "/opt/hostedtoolcache/Python/3.11.3/x64/bin/allure-combine", line 8, in <module>

> Checking for folder contents

  sys.exit(main())

            ^^^^^^

File "/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/allure_combine/combine.py", line 302, in main

combine_allure(args.folder.rstrip(sep), args.dest, args.remove_temp_files, args.auto_create_folders, args.ignore_utf8_errors)

File "/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/allure_combine/combine.py", line 251, in combine_allure

with open(file_path, "r", encoding="utf8") as ff:

        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

FileNotFoundError: [Errno 2] No such file or directory: 'Samsung Galaxy S21-allure-results-html/https://www.googletagmanager.com/gtag/js?id=G-FVWC4GKEYS'
```

**Comment by MihanEntalpo** [comment]
Thanks for your feedback. Can you upload your allure generated folder so I can check it? It seems, that the problem caused by Google tag manager added to allure html file for some unknown reason, and the fact, that my script cannot handle such urls the right way

**Comment by yarniko** [comment]
I have the same problem. Do you have any news about this?

**Comment by MihanEntalpo** [comment]
Hi! I've pushed new version into github, which has  this problem solved. Now struggling to upload package into pypi, so it could be updated easily (have some problems with "This filename has already been used"). 
After I could upload it, I've let you know.
Now you can use this repo current version of main branch

**Comment by MihanEntalpo** [comment]
Good news everyone! I've uploaded version 1.0.10 to pypi, that has this problem solved. Try it out, and if you still have problems with FileNotFoundError, feel free to reopen this issue
