### ISSUE TITLE
description error show with block <pre><code>

### ISSUE THREAD

**Issue by xianyo** [MihanEntalpo/allure-single-html-file#28]
description error show with block <pre><code>:

<pre><code> this is description  </code></pre>

**Comment by MihanEntalpo** [comment]
Hello. Please give more information. Also it'll be good to have your allure-generated folder attached

**Comment by MihanEntalpo** [comment]
(I'm surely should create issue template)

**Comment by xianyo** [comment]
![企业微信截图_16903573611139](https://github.com/MihanEntalpo/allure-single-html-file/assets/4560040/97f368ff-e6c6-46dc-852a-79857edf1d7b)

**Comment by xianyo** [comment]
pre  code block not translate into html show。 it show the pre code string in description

**Comment by MihanEntalpo** [comment]
Unfortunately this is a known bug, that is also mentioned here https://github.com/MihanEntalpo/allure-single-html-file/issues/18. Right now, all I've tried to do with this problem had no effect, or just broke the interface.
Some day I'll fix it, or maybe someone else will propose pull request with such a fix

**Comment by MihanEntalpo** [comment]
According to this merged pull request allure-framework/allure2#2072 Allure itself now has command line argument --single-file that make it produce report as a single html file. As for now it's not described in official allure docs, but anyway it should make this package (allure-combine) useless. I'm encorage you to use Allure --single-file functionality, as it should work much better that my combiner!
