### ISSUE TITLE
Not working in Windows 10 due to backslash? (original issue fixed, here's new one)

### ISSUE THREAD

**Issue by teverus** [MihanEntalpo/allure-single-html-file#3]
Hello, guys! I've had an issue while using your program :( I believe it's because of / and \ in Linux vs Windows. Is there a workaround? :)
![01_02_2022__07_48_14](https://user-images.githubusercontent.com/62369371/151914356-a6b89517-f968-40a1-83a2-aab3ab8764d9.png)

**Comment by MihanEntalpo** [comment]
@teverus I've just created "windows" branch where I've tried to fix your problem. Try it out and if it's working, I'll test it on linux and merge into main branch.

**Comment by MihanEntalpo** [comment]
@teverus wait, found a bug :) check it out after 30 minutes or so

**Comment by teverus** [comment]
Sure think, man! Thank you :) Just tell me when you're ready and I'll check locally :)

**Comment by MihanEntalpo** [comment]
@teverus done!

**Comment by teverus** [comment]
checking...

**Comment by teverus** [comment]
Well, we have a new error :)
![01_02_2022__09_05_36](https://user-images.githubusercontent.com/62369371/151920569-a157072c-78df-475e-9c0e-2922d6f14ae7.png)

**Comment by MihanEntalpo** [comment]
@teverus Ok, fixed encoding problem. Try it. 
Sometimes I forget why did I switched from windows to linux for decade ago and such cases remember me :)

**Comment by teverus** [comment]
I'm starting hating Windows as well :) Sorry, dude, but there is one more line to fix :(
![01_02_2022__09_39_17](https://user-images.githubusercontent.com/62369371/151923436-cb04f4ef-e7b5-4887-abdb-c688149c51d3.png)

**Comment by MihanEntalpo** [comment]
@teverus and try again :)

**Comment by teverus** [comment]
Good news is that it worked :) Thanks :)
![01_02_2022__09_49_28](https://user-images.githubusercontent.com/62369371/151924622-e5243442-8bae-4236-875c-90b584f19c98.png)
Bad news
![01_02_2022__09_49_04](https://user-images.githubusercontent.com/62369371/151924664-e200503a-3b65-4200-90d3-1de0b694b0fe.png)
Do I need to generate an allure report somehow differently? Do I need to use this --allow-file-access-from-files or is this an argument for Chrome only?

**Comment by MihanEntalpo** [comment]
Sid you tried to open both index.html and complete.html?

**Comment by teverus** [comment]
Yep :(
![01_02_2022__10_19_49](https://user-images.githubusercontent.com/62369371/151927640-8069c9fc-0b53-44ee-98aa-b67eb9466265.png)

**Comment by MihanEntalpo** [comment]
@teverus Please, open DevTools in browser, then Network tab, and reload index.html file.
I need a screenshot of all the requests, and detailed screenshot of one bad requests (red one) opened by clicking on it

**Comment by teverus** [comment]
I can see no requests with an error :(
![01_02_2022__10_54_06](https://user-images.githubusercontent.com/62369371/151931385-98d5db43-a15e-4fe4-9d6d-da0c7086c156.png)

**Comment by MihanEntalpo** [comment]
Ok. Can you please generate some example allure report folder and attach it as a zip file? I'll test in in my VirtualBox with Windows installed. I dont have allure installed in windows so I need pregenerated folder

**Comment by teverus** [comment]
Here you go. Thank you very much :)
[allure-report.zip](https://github.com/MihanEntalpo/allure-single-html-file/files/7976893/allure-report.zip)

**Comment by MihanEntalpo** [comment]
Thanks. Will look into it today. At first sight: very strange files naming (with slashes in filenames). It seems that promblem root must be somethere near :)

**Comment by MihanEntalpo** [comment]
@teverus truns out it was another one slash-direction problem, at this time with urls inside the document. Try it out now.

**Comment by teverus** [comment]
It works! Thank you so much :) Now, this wonderful application is suitable for Windows as well :) Thank you!

**Comment by kanjums** [comment]
This doesnt work for me in windows 10...complete.html does not have any data

**Comment by MihanEntalpo** [comment]
@kanjums please upload your allure folder, so I could check what happens. And, also, show screenshow of opened devtools of browser where complete.html is opened in the "Console" tab, and show your console output when the command is called

**Comment by kanjums** [comment]
Hi,
I am attaching both the files. I dont see anything in console though when complete.html is accessed in chrome.
[allure-report.zip](https://github.com/MihanEntalpo/allure-single-html-file/files/9408631/allure-report.zip)
<img width="960" alt="complete_devtools_ss" src="https://user-images.githubusercontent.com/111879835/186221874-9a33e3f5-bbd1-4634-bf12-38a3659d6b03.png">

Thanks

**Comment by MihanEntalpo** [comment]
@kanjums your allure generated folder is somehow broken, because it's not opening without any allure-combine transformation.
I've tried to run chrome with arguments `--allow-file-access-from-files --disable-web-security` to allow it to open local files, and opened your index.html file from the folder you supplied. And it gives me the same sad screen as you have:

![Screenshot_20220824_135759](https://user-images.githubusercontent.com/3025716/186352083-0861dcc1-c824-4417-9774-eaf061faba16.png)

So, there is nothing to do with allure-combine script, your allure report is not working by itself, and you have to investigate this firts

**Comment by kanjums** [comment]
sure but my allure report does have data:
<img width="955" alt="allurereport" src="https://user-images.githubusercontent.com/111879835/186361935-8de0c160-d127-40ae-a6f6-49661f9e0ea0.png">
Thanks

**Comment by MihanEntalpo** [comment]
Please, try to launch your chrome browser with arguments `--allow-file-access-from-files --disable-web-security` and open index.html file with it. Need to check, maybe the problem root is in some difference between file opened from filesystem or file loaded from temporary allure web server (dont forget to close browser and restart it without arguments, as it's not safe to use it in normal browsing)

**Comment by MihanEntalpo** [comment]
I mean index.html from th efilesystem, not from allure web-server

**Comment by kanjums** [comment]
ok, when i open with chrome then index.html has no data ..it has data only when its generated with webserver..

**Comment by MihanEntalpo** [comment]
And how does it looks like when opening from filesystem? Can you attach a screenshot please?

**Comment by MihanEntalpo** [comment]
I'll try your report on some simple http server to check whats the difference between it serving and loading from filesystem. 
Wy the way, what version of allure do you have?

**Comment by kanjums** [comment]
same as yours 
<img width="957" alt="image" src="https://user-images.githubusercontent.com/111879835/186369435-68c06d2b-29ad-4832-b68a-cf19fd64c3e4.png">

**Comment by kanjums** [comment]
Same as yours :
<img width="947" alt="image" src="https://user-images.githubusercontent.com/111879835/186369701-f1f539f8-a8d7-429b-8d7a-2afd47f9e7b0.png">

**Comment by MihanEntalpo** [comment]
Ok, strange but interesting. Didn't see such allure report yet, maybe something has changed in the allure generator algorythm.

**Comment by kanjums** [comment]
allure version is 2.18.1
Thanks

**Comment by MihanEntalpo** [comment]
As you can see, when serving your allure-report folder from simple http server, I get no difference with just opening index.html from the filesystem.
![image](https://user-images.githubusercontent.com/3025716/186651219-9d557454-4bc8-4efd-ace8-dd72343f2825.png)

Please, after opening allure-report by allure web-server, open devtools->network, and make screenshot of file summary.json.
This file is responsble for the big ugly NaN in my screenshot and nice zero on your screenshot. So I need to see, if the file differs. Thanks.
If your file would differs from the one I've showed on screenshot, please look into filesystem, and check, if file contents is the same as in your browser devtool. If it's so, please pack your new allure-report folder and upload it here

**Comment by kanjums** [comment]
Its same as yours 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/111879835/186681511-cfa95e26-4d38-4e6a-87b9-f27ee42f9b89.png">

**Comment by MihanEntalpo** [comment]
I see a single method of investiagtion of this problem. As I don't have allure installed, and also your test project what is generating data for the allure, I need to communicate with you via some kind of remote access application, like AnyDesk, and examine all the difference between "work from web-server" and "work from filesystem" in your own browser.
If you ok with that - write me to mihanentalpo@yandex.ru and we'll connect at convinient time.

**Comment by MihanEntalpo** [comment]
Closing for now due to no feedback.
Original issue is solved, if you have new one - please create new issue.
