### ISSUE TITLE
Can we have support for mp4 video files as well?

### ISSUE THREAD

**Issue by kivysyar** [MihanEntalpo/allure-single-html-file#5]
This tool is so amazing and working perfectly. Can you please add support for mp4 video files as well?

**Comment by kivysyar** [comment]
@MihanEntalpo Appreciate your prompt response. I've already tried this, it is not working. It is still referring to the file path. Please check and revert!

**Comment by MihanEntalpo** [comment]
@kivysyar I have no allure-generated folder with mp4 files right now, so cannot fully check new version.
Please give information about problems that you got. Error messages, screenshots and so on.

**Comment by MihanEntalpo** [comment]
Console output of your script run also would be useful

**Comment by kivysyar** [comment]
![image](https://user-images.githubusercontent.com/93857414/166107765-ee272545-cfc0-4e77-a631-82cc71e0c279.png)
Here is the console output, but there are no errors.

**Comment by kivysyar** [comment]
I've also sent the sample report to your mail. Please check!

**Comment by MihanEntalpo** [comment]
@kivysyar Thanks to your allure folder that you've sent me, I've found and fixed bug in js module that was responsible for some glitches of not working attachments. Also I've added support for <source> tag inside of <video>, that made your example fork by opening generated complete.html.
Try it now

**Comment by kivysyar** [comment]
@MihanEntalpo This is working fine now, thanks a ton!
