### ISSUE TITLE
[Question]: will you add another argument(dest_path, etc...) as the path that the complete.html stored

### ISSUE THREAD

**Issue by kisscelia** [MihanEntalpo/allure-single-html-file#8]
when complete.html stored in the allure-report folder, allure web will not worked as well.

Great works, thanks.

**Comment by MihanEntalpo** [comment]
What do you mean on "allure web will not worked as well"? 
Adding parameters allowing to save output file to other location is one of planned future enhancements.
If you have some specific problem right bow, you can change path to "complete.html" right in the code, it's easy.

**Comment by MihanEntalpo** [comment]
Line to change the output path is here https://github.com/MihanEntalpo/allure-single-html-file/blob/main/combine.py#L241

**Comment by kisscelia** [comment]
Hi, @MihanEntalpo 
I made a pull request, thanks.
https://github.com/MihanEntalpo/allure-single-html-file/pull/9

**Comment by kisscelia** [comment]
closed
